# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: Icon Card
  description: Icon card
  icon: 'style'
  tags:
    - Card
    - Icon

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
  text:
  icon:
  link:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  icon:
    type: select
    values: data.icons
    hidden: 'image'
  type:
    type: select
    label: Card type
    options:
      values:
        - icons
        - images
  image:
    hidden: 'icon'
