# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Featured - Large feature
  description: Featured stories grid
  icon: "chrome_reader_mode"
  tags: []
  picker_preview:
    gallery:
      image: /images/component-screenshots/featured-large.png

# Defines the structure of this component, as well as the default values
blueprint:
  main_feature: ""
  feature_list: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
