# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Form"
  description: A CloudCannon form with a heading
  icon: dynamic_form
  tags: ['form']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    id:
    heading: 
    description: Description text to compliment the block
    form:
      id: 
      form_submission_type: email/cloudcannon
      inbox_key: 
      subject:
      success_page: ""
      form_elements: [bookshop:structure:form_blocks]
      submit_button:
        text: "Button text"
        variant: "primary"
        arrow: "right"
  styles:
    background_color: '#000000'
    text_color: '#ffffff'
    placeholder_text_color: '#F9F9FB'
    content_alignment: center

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:  
  placeholder_text_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
