# Metadata about this component, to be used in the CMS
spec:
  structures:
    - cards
  label: Background Image Card
  description:
  icon: 'style'
  tags:
    - Card
    - Image

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    heading_text: Want bread?
    heading_color: '#FFFFFF'
  subheading:
    subheading_text: Where to find our loaves.
    subheading_color: '#FFFFFF'
  background_image:
    image_path: /src/assets/images/bakery-shots/1ECE93C3-8924-4ADF-8CDB-1A02D6D1CC04 2.jpg
    image_alt: 'A bakery shot'
    filters:
      brightness: 0.6
      grayscale: 0.2
  link: '/bread/'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background_image:
    options:
      preview:
        icon: image
        image:
          - key: image_path
        text: Background Image
        subtext:
          - key: image_alt
          - Update background image
